Dark mode enabled | Navbar modifications | Mobile menu modifications
trypear/pear-landing-page pull request #166
Opened 2024-07-13 12:49 UTC by tanishq-xin

![image](https://github.com/user-attachments/assets/1aa117cc-0937-4bc0-a284-8c16258c7d5f)

![image](https://github.com/user-attachments/assets/af547b8b-cfe3-4a76-8d1f-1217095bfb0d)

2024-07-13 15:22 UTC, Ellahinator commented on app/layout.tsx
`<PHProvider>` should go outside the `body`

2024-07-13 22:54 UTC, ICEPrey requested changes
couple of changes

2024-07-13 22:54 UTC, ICEPrey commented on .hintrc
remove this file since we already have a .eslintrc config file

2024-07-13 22:54 UTC, ICEPrey commented on app/globals.css
> +
```suggestion
```

Remove this, throwing error + pan didn't decide on a font yet

2024-07-13 22:54 UTC, ICEPrey commented on components/auth/signup.tsx
>                      </span>
```suggestion
                    <span>Sign up with GitHub</span>
```

2024-07-13 22:54 UTC, ICEPrey commented on components/auth/signup.tsx
> +                      className="border-[white] mr-4 flex h-6 items-center border-r border-opacity-50 dark:border-opacity-40"
remove comments/not used code

2024-07-13 22:54 UTC, ICEPrey commented on components/auth/signup.tsx
>                  </span>
```suggestion
                <span>Sign up with Google</span>
```

2024-07-13 22:54 UTC, ICEPrey commented on components/auth/signup.tsx
> +                {/* <span
also remove comments/unused code here

2024-07-13 22:54 UTC, ICEPrey commented on public/nka.png
What is this? lol

2024-07-13 22:54 UTC, ICEPrey commented on components/auth/signin.tsx
>                  </span>
```suggestion               
 <span>Sign up with Google</span>
```

2024-07-13 22:54 UTC, ICEPrey commented on components/auth/signin.tsx
> +                /> */}
remove comment

2024-07-13 22:54 UTC, ICEPrey commented on components/auth/signin.tsx
> +                    /> */}
remove comment

2024-07-13 22:54 UTC, ICEPrey commented on components/auth/signin.tsx
>                      </span>
```suggestion
                    <span>Sign in with GitHub</span>
```

2024-07-13 22:54 UTC, ICEPrey commented on components/about.tsx
> +      className="to-white bg-gradient-to-b from-gray-50 px-4 py-12 pt-20 dark:bg-none"
```suggestion
      className="to-white bg-gradient-to-b from-gray-50 px-4 py-12 pt-20"
```

2024-07-13 22:54 UTC, ICEPrey commented on components/ui/authbutton.tsx
> +            className="transition duration-150 ease-in-out hover:text-gray-700"
```suggestion
            className="text-gray-800 transition duration-150 ease-in-out hover:text-primary-800"
```

2024-07-13 22:54 UTC, ICEPrey commented on components/ui/authbutton.tsx
> +            className="transition duration-150 ease-in-out hover:text-gray-700"
```suggestion
            className="text-gray-800 transition duration-150 ease-in-out hover:text-primary-800"
```

2024-07-13 22:54 UTC, ICEPrey commented on components/ui/authbutton.tsx
> +            className="transition duration-150 ease-in-out hover:text-gray-700"
```suggestion
            className="text-gray-800 transition duration-150 ease-in-out hover:text-primary-800"

```

2024-07-13 22:54 UTC, ICEPrey commented on components/ui/authbutton.tsx
> +            <button className="transition duration-150 ease-in-out hover:text-gray-700">
```suggestion
            <button className="text-gray-800 transition duration-150 ease-in-out hover:text-primary-800">
```

2024-07-13 22:54 UTC, ICEPrey commented on components/ui/header.tsx
> +                        className="align-middle hover:text-gray-700"
```suggestion
                        className="align-middle text-gray-800 transition duration-150 ease-in-out hover:text-primary-800"
```

2024-07-13 23:16 UTC, tanishq-xin commented on public/nka.png
whoops must have got it here by mistake

2024-07-14 07:49 UTC, Fryingpannn reviewed
- The about page was updated (see https://trypear.ai/about). Needs some fixing in this PR 👀. If too much to merge the conflicts correctly, may be easier to directly copy the current file and simply add dark mode to it.
- Mobile responsiveness for the bottom buttons
<img width="395" alt="Screenshot 2024-07-14 at 3 45 58 PM" src="https://github.com/user-attachments/assets/32ad1777-d141-4dc4-a320-6021cab4de12">
<img width="358" alt="Screenshot 2024-07-14 at 3 46 15 PM" src="https://github.com/user-attachments/assets/25350509-b64c-4fab-96af-237cb9318cf8">

2024-07-14 11:43 UTC, Fryingpannn approved these changes

2024-07-14 11:43 UTC, merged