Add active state to navbar links
trypear/pear-landing-page pull request #180
Opened 2024-07-22 15:13 UTC by SHADOW-LIGHTS

### Related Issue
- #179 

### Changes Made
- Implemented active state styling for navbar links.
- Extracted navigation links into a separate Navigation component.

### Screenshots
**Before**
<img width="960" alt="image" src="https://github.com/user-attachments/assets/dafadb75-d577-41b1-ac70-8728d07ba433">

**After**
<img width="960" alt="image" src="https://github.com/user-attachments/assets/5e257ce3-3dcb-4cc6-b92a-dd6f54c2d6bc">

### Checklist

- [x] I have tagged the issue in this PR.
- [x] I have attached necessary screenshots.
- [x] I ran `yarn build` and build is successful
- [x] My code follows the style guidelines of this project.

2024-07-22 19:10 UTC, Ellahinator approved these changes

2024-07-22 19:10 UTC, Ellahinator requested changes
this pr is removing `.env.local.example`. we need to keep this file

2024-07-24 06:17 UTC, SHADOW-LIGHTS commented
> this pr is removing `.env.local.example`. we need to keep this file

added the .env.local.example

2024-07-24 08:56 UTC, Ellahinator approved these changes

2024-07-24 18:27 UTC, Fryingpannn approved these changes

2024-07-24 18:29 UTC, merged