Add Geist Typeface to Project
trypear/pear-landing-page pull request #197
Opened 2024-08-06 13:24 UTC by SHADOW-LIGHTS

### Description
Integrated the Geist typeface into the project to enhance readability and design consistency. This addition aims to improve the visual experience for both developers and users.

### Related Issue
#196 

### Changes Made
- Added Geist Sans variant for versatile design use.
- Included Geist monospace variant for improved code readability.
- Updated Tailwind config and CSS files to apply the new typeface across the project.

### Screenshots
**Now -**
<img width="958" alt="image" src="https://github.com/user-attachments/assets/18157d07-968c-49b0-9b20-e22a47ae2110">
**Before -**
<img width="957" alt="image" src="https://github.com/user-attachments/assets/8689adf2-7700-42b8-81be-e8d1afd77545">

### Checklist

- [x] I have tagged the issue in this PR.
- [x] I have attached necessary screenshots.
- [x] I have provided a short description of the PR.
- [x] I ran `yarn build` and build is successful
- [x] My code follows the style guidelines of this project.
- [x] I have added necessary documentation (if applicable)

2024-08-06 13:32 UTC, SHADOW-LIGHTS commented
This font truly goes with the story of the company. While images might not fully capture the impact of this change, the improved readability and design consistency will surely enhance the user experience. 
It’ll blend seamlessly with all the future changes and fit perfectly with other elements.

2024-08-07 02:38 UTC, ICEPrey commented on app/layout.tsx
> +          className={`--font-geist-sans bg-background tracking-tight text-gray-900 antialiased`}
This is wrong we should just use the tailwind class to apply the font
```suggestion
          className={`font-sans bg-background tracking-tight text-gray-900 antialiased`}
```

2024-08-07 02:38 UTC, ICEPrey requested changes
minor change

2024-08-07 13:54 UTC, SHADOW-LIGHTS commented
> minor change

bad mistake. Corrected it

2024-08-07 16:43 UTC, ICEPrey approved these changes
looks good to me

2024-08-09 18:44 UTC, Fryingpannn approved these changes

2024-08-09 18:44 UTC, merged