Fix footer
trypear/pear-landing-page pull request #269
Opened 2024-09-05 14:27 UTC by ompathak2004

### Description

Footer  component has been integrated into the RootLayout component to ensure consistent placement across all pages. 

### Related Issue

### Changes Made

### Screenshots

### Checklist

- [ ] I have tagged the issue in this PR.
- [ ] I have attached necessary screenshots.
- [ ] I have provided a short description of the PR.
- [x] I ran `yarn build` and build is successful
- [x] My code follows the style guidelines of this project.
- [ ] I have added necessary documentation (if applicable)

2024-09-07 16:54 UTC, Ellahinator requested changes

2024-09-07 16:54 UTC, Ellahinator commented on next-env.d.ts
this file should not be edited

2024-09-07 17:41 UTC, ompathak2004 commented on next-env.d.ts
Reverted change

2024-09-07 23:08 UTC, ICEPrey approved these changes

2024-09-08 00:54 UTC, Ellahinator approved these changes

2024-09-08 03:44 UTC, Fryingpannn approved these changes

2024-09-08 03:44 UTC, merged

2024-09-12 08:25 UTC, SHADOW-LIGHTS commented
Dashboard should not have footer