fix: scroll bar hiding on pricing page #281
trypear/pear-landing-page pull request #284
Opened 2024-09-14 10:14 UTC by olesuv

### Description

scroll bar is till appeared after triggering drop down menu.

### Related Issue

#281

### Changes Made

added modal tag for `DropdownMenu` tag, related fix radix-ui: https://github.com/radix-ui/primitives/issues/1272#issuecomment-1136899602

### Screenshots

![image](https://github.com/user-attachments/assets/7090f88b-66d6-4e5a-a7b9-012e7ceedda8)

### Checklist

- [x] I have tagged the issue in this PR.
- [x] I have attached necessary screenshots.
- [x] I have provided a short description of the PR.
- [x] I ran `yarn build` and build is successful
- [x] My code follows the style guidelines of this project.
- [ ] I have added necessary documentation (if applicable)

2024-09-14 16:00 UTC, ICEPrey commented on next-env.d.ts
This file should not be commited

2024-09-14 16:00 UTC, ICEPrey requested changes
remove next-env.d.ts and then should be good to go

2024-09-14 16:01 UTC, Ellahinator requested changes

2024-09-14 16:01 UTC, Ellahinator commented on next-env.d.ts
this file shouldn't be edited

2024-09-14 16:12 UTC, olesuv commented
> remove next-env.d.ts and then should be good to go

like the whole file should not be present or the line should be restored?

2024-09-14 16:14 UTC, ICEPrey commented
> > remove next-env.d.ts and then should be good to go
> 
> like the whole file should not be present or the line should be restored?

line should be restored

2024-09-14 16:21 UTC, ICEPrey approved these changes
good to go (this happend on navbar before https://github.com/trypear/pear-landing-page/pull/221/commits/83710bca28d202e6b2353be67d73b31bbd56c2ee)

2024-09-15 03:38 UTC, Fryingpannn approved these changes

2024-09-15 03:39 UTC, merged