Navbar styling changes
trypear/pear-landing-page pull request #82
Opened 2024-06-23 17:02 UTC by Ellahinator

I decided to make some changes to the navbar as I believe it is too big and not a big fan of the gradient background. I gained inspiration from Apple's navbar:
![image](https://github.com/trypear/pear-landing-page/assets/87584757/b56663d5-c87b-47d6-980e-bf3ff54cfe63)

Changes:
1. Removed gradient bg
2. Height smaller
3. Fixed the Pear Logo SVG removing awkward empty space 
4. Font smaller 
5. Increased bg blur
6. Using secondary colors instead of gray
7. Centered Hamburger icon on mobile
8. Added small shadow

Desktop:
| Before | After |
| --- | --- |
| ![image](https://github.com/trypear/pear-landing-page/assets/87584757/26eb2249-553b-4bbf-9457-e72b52c0f70f) |  ![image](https://github.com/trypear/pear-landing-page/assets/87584757/48d8c101-439d-4be4-8cc9-6d51a67f73ee) |

Mobile:
| Before | After |
| --- | --- |
| ![image](https://github.com/trypear/pear-landing-page/assets/87584757/12c8bb7d-5ee1-4dea-a8ae-63443261cf1c) | ![image](https://github.com/trypear/pear-landing-page/assets/87584757/725f12a5-2ac8-4df0-8b42-7601d49cf358) |

2024-06-23 21:40 UTC, Fryingpannn reviewed
Yo use this for logo!

https://drive.google.com/file/d/1oJwD9mSHUctNRFGuzysC0xhTMibwMBx3/view?usp=sharing

2024-06-23 21:40 UTC, Fryingpannn commented on components/ui/header.tsx
> +    <header className="md: fixed top-0 z-30 w-full animate-fadein-opacity bg-white-50 bg-opacity-80 shadow-sm backdrop-blur-[16px]">
```suggestion
    <header className="md:fixed top-0 z-30 w-full animate-fadein-opacity bg-white-50 bg-opacity-80 shadow-sm backdrop-blur-[16px]">
```

2024-06-23 21:40 UTC, Fryingpannn commented on components/ui/mobile-menu.tsx
> +        className={`hamburger hover:text-gray-600 ${mobileNavOpen && "active"} flex`}
```suggestion
        className={`hamburger hover:text-gray-600 ${mobileNavOpen ? "active" : ""} flex`}
```

2024-06-23 21:40 UTC, Fryingpannn commented on components/ui/header.tsx
> +                  key={index}
```suggestion
                  key={link.label}
```

2024-06-23 22:13 UTC, Ellahinator commented on components/features.tsx
> +      header: "Talk to your codebase directly",
im not sure why this is being shown as a change. this is the same as main. 😕

2024-06-24 07:09 UTC, ICEPrey requested changes
Minor changes since we are going to start focusing on SEO

2024-06-24 07:09 UTC, ICEPrey commented on components/ui/header.tsx
> +            <div className="flex space-x-2">
```suggestion
            <ul className="flex space-x-2">
```

2024-06-24 07:09 UTC, ICEPrey commented on components/ui/header.tsx
>              {/* Nav titles */}
```suggestion
            {/* Nav titles */}
                  <nav>
```
wrap it in nav since we are going to be start focusing on seo

2024-06-24 07:09 UTC, ICEPrey commented on components/ui/header.tsx
> +              {navLinks.map((link, index) => (
after we map navLinks you need to wrap each item in an li tag when using an unordered list (ul)
 ```js
<li key={link.label}>
```

2024-06-24 07:09 UTC, ICEPrey commented on components/ui/header.tsx
> +                <Link
```suggestion
                <Link className="hover:text-secondary-400" href={link.path}>
```
now we can remove the 
```js
key={link.label}
```

2024-06-24 07:09 UTC, ICEPrey commented on components/ui/header.tsx
> +                </Link>
add ending tag
```js
  </li>
```

2024-06-24 07:09 UTC, ICEPrey commented on components/ui/header.tsx
> +            </div>
now before the closing the div we add closing 
```js
</ul> and </nav>
```

2024-06-24 17:30 UTC, ICEPrey approved these changes

2024-06-28 01:57 UTC, Fryingpannn approved these changes

2024-06-28 01:57 UTC, merged